// prisma/seed.ts
import { db } from "../src/lib/prisma";

type Q = {
  category: string;
  prompt: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  answer: "A" | "B" | "C" | "D";
  explanation?: string;
};

const questions: Q[] = [
  // ─── General Bible Knowledge (25 questions) ─────────────────────────────────
  {
    category: "general",
    prompt: "How many books are in the Bible?",
    optionA: "66",
    optionB: "72",
    optionC: "39",
    optionD: "80",
    answer: "A",
    explanation: "The Bible contains 66 books: 39 in the Old Testament and 27 in the New Testament.",
  },
  {
    category: "general",
    prompt: "What is the shortest verse in the Bible?",
    optionA: "God is love.",
    optionB: "Amen.",
    optionC: "Jesus wept.",
    optionD: "Pray always.",
    answer: "C",
    explanation: "John 11:35 — 'Jesus wept.' — is the shortest verse in most English translations.",
  },
  {
    category: "general",
    prompt: "In what city was Jesus born?",
    optionA: "Nazareth",
    optionB: "Jerusalem",
    optionC: "Jericho",
    optionD: "Bethlehem",
    answer: "D",
    explanation: "Jesus was born in Bethlehem, fulfilling the prophecy in Micah 5:2.",
  },
  {
    category: "general",
    prompt: "Who baptized Jesus?",
    optionA: "Peter",
    optionB: "John the Baptist",
    optionC: "Andrew",
    optionD: "The Holy Spirit",
    answer: "B",
    explanation: "John the Baptist baptized Jesus in the Jordan River (Matthew 3:13–17).",
  },
  {
    category: "general",
    prompt: "What was the first miracle Jesus performed?",
    optionA: "Healing a blind man",
    optionB: "Raising Lazarus",
    optionC: "Feeding five thousand people",
    optionD: "Turning water into wine",
    answer: "D",
    explanation: "Jesus turned water into wine at a wedding in Cana (John 2:1–11).",
  },
  {
    category: "general",
    prompt: "How many disciples did Jesus choose?",
    optionA: "7",
    optionB: "10",
    optionC: "12",
    optionD: "70",
    answer: "C",
    explanation: "Jesus chose twelve disciples, also called apostles (Luke 6:12–16).",
  },
  {
    category: "general",
    prompt: "Who denied Jesus three times before the rooster crowed?",
    optionA: "Judas",
    optionB: "Thomas",
    optionC: "John",
    optionD: "Peter",
    answer: "D",
    explanation: "Peter denied knowing Jesus three times, just as Jesus had predicted (Luke 22:54–62).",
  },
  {
    category: "general",
    prompt: "What is the last book of the Bible?",
    optionA: "Jude",
    optionB: "Revelation",
    optionC: "Hebrews",
    optionD: "Malachi",
    answer: "B",
    explanation: "The book of Revelation is the final book of the New Testament and the entire Bible.",
  },
  {
    category: "general",
    prompt: "Who was swallowed by a great fish?",
    optionA: "Elijah",
    optionB: "Isaiah",
    optionC: "Jonah",
    optionD: "Daniel",
    answer: "C",
    explanation: "Jonah was swallowed by a great fish after fleeing God's call to preach to Nineveh (Jonah 1:17).",
  },
  {
    category: "general",
    prompt: "For how many days and nights did it rain during Noah's flood?",
    optionA: "7",
    optionB: "20",
    optionC: "40",
    optionD: "150",
    answer: "C",
    explanation: "It rained for forty days and forty nights during the great flood (Genesis 7:12).",
  },
  {
    category: "general",
    prompt: "Who was the first king of Israel?",
    optionA: "David",
    optionB: "Solomon",
    optionC: "Saul",
    optionD: "Samuel",
    answer: "C",
    explanation: "Saul was anointed by Samuel as the first king of Israel (1 Samuel 10:1).",
  },
  {
    category: "general",
    prompt: "Which Psalm begins with 'The Lord is my shepherd'?",
    optionA: "Psalm 1",
    optionB: "Psalm 23",
    optionC: "Psalm 91",
    optionD: "Psalm 119",
    answer: "B",
    explanation: "Psalm 23, written by David, begins with 'The Lord is my shepherd; I shall not want.'",
  },
  {
    category: "general",
    prompt: "Who climbed a sycamore tree to see Jesus?",
    optionA: "Matthew",
    optionB: "Nicodemus",
    optionC: "Zacchaeus",
    optionD: "Bartimaeus",
    answer: "C",
    explanation: "Zacchaeus, a short tax collector, climbed a sycamore tree to see Jesus in Jericho (Luke 19:1–4).",
  },
  {
    category: "general",
    prompt: "What is the first book of the Bible?",
    optionA: "Exodus",
    optionB: "Psalms",
    optionC: "Job",
    optionD: "Genesis",
    answer: "D",
    explanation: "Genesis is the first book of the Bible, beginning with creation.",
  },
  {
    category: "general",
    prompt: "Which apostle is known as 'the doubter' for questioning the resurrection?",
    optionA: "Philip",
    optionB: "Bartholomew",
    optionC: "Thomas",
    optionD: "James",
    answer: "C",
    explanation: "Thomas said he would not believe unless he saw and touched Jesus' wounds (John 20:24–25).",
  },
  {
    category: "general",
    prompt: "On what day did God rest after creation?",
    optionA: "Fifth",
    optionB: "Sixth",
    optionC: "Seventh",
    optionD: "Eighth",
    answer: "C",
    explanation: "God rested on the seventh day and declared it holy (Genesis 2:2–3).",
  },
  {
    category: "general",
    prompt: "Who wrote most of the Psalms?",
    optionA: "Moses",
    optionB: "Solomon",
    optionC: "Asaph",
    optionD: "David",
    answer: "D",
    explanation: "King David is credited with writing 73 of the 150 Psalms.",
  },
  {
    category: "general",
    prompt: "In which river was Jesus baptized?",
    optionA: "Nile",
    optionB: "Euphrates",
    optionC: "Jordan",
    optionD: "Galilee",
    answer: "C",
    explanation: "Jesus was baptized in the Jordan River by John the Baptist (Matthew 3:13).",
  },
  {
    category: "general",
    prompt: "Who wrote most of the letters in the New Testament?",
    optionA: "Peter",
    optionB: "Paul",
    optionC: "John",
    optionD: "Luke",
    answer: "B",
    explanation: "The Apostle Paul authored 13 of the 27 New Testament books.",
  },
  {
    category: "general",
    prompt: "What were the names of Abraham's two sons?",
    optionA: "Jacob and Esau",
    optionB: "Ishmael and Isaac",
    optionC: "Cain and Abel",
    optionD: "Shem and Ham",
    answer: "B",
    explanation: "Abraham's sons were Ishmael (by Hagar) and Isaac (by Sarah).",
  },
  {
    category: "general",
    prompt: "How many days was Jesus in the wilderness before his temptation?",
    optionA: "3",
    optionB: "7",
    optionC: "30",
    optionD: "40",
    answer: "D",
    explanation: "Jesus fasted and was tempted by the devil for forty days in the wilderness (Matthew 4:1–2).",
  },
  {
    category: "general",
    prompt: "What did Jesus say are the two greatest commandments?",
    optionA: "Honor your parents and do not kill",
    optionB: "Love God and love your neighbor",
    optionC: "Keep the Sabbath and tithe",
    optionD: "Pray always and fast often",
    answer: "B",
    explanation: "Jesus said to love God with all your heart and to love your neighbor as yourself (Matthew 22:37–39).",
  },
  {
    category: "general",
    prompt: "Which disciple betrayed Jesus for thirty pieces of silver?",
    optionA: "Thomas",
    optionB: "Peter",
    optionC: "Bartholomew",
    optionD: "Judas Iscariot",
    answer: "D",
    explanation: "Judas Iscariot betrayed Jesus to the chief priests for thirty pieces of silver (Matthew 26:14–16).",
  },
  {
    category: "general",
    prompt: "Where did Jesus deliver the Sermon on the Mount?",
    optionA: "Temple in Jerusalem",
    optionB: "Shore of the Sea of Galilee",
    optionC: "A hillside in Galilee",
    optionD: "Garden of Gethsemane",
    answer: "C",
    explanation: "Jesus delivered the Sermon on the Mount on a hillside in Galilee (Matthew 5:1–2).",
  },
  {
    category: "general",
    prompt: "What sign did God place in the sky as a covenant with Noah?",
    optionA: "A star",
    optionB: "A rainbow",
    optionC: "A cloud",
    optionD: "Lightning",
    answer: "B",
    explanation: "God placed a rainbow in the sky as a sign of his covenant never to flood the earth again (Genesis 9:13).",
  },

  // ─── Women of the Bible (22 questions) ──────────────────────────────────────
  {
    category: "women",
    prompt: "Who was the first woman, created from Adam's rib?",
    optionA: "Lilith",
    optionB: "Miriam",
    optionC: "Eve",
    optionD: "Sarah",
    answer: "C",
    explanation: "Eve was created from Adam's rib and is the first woman in Scripture (Genesis 2:21–22).",
  },
  {
    category: "women",
    prompt: "Who said 'Where you go I will go, and where you lodge I will lodge'?",
    optionA: "Esther",
    optionB: "Ruth",
    optionC: "Hannah",
    optionD: "Miriam",
    answer: "B",
    explanation: "Ruth spoke these words of loyalty to her mother-in-law Naomi (Ruth 1:16).",
  },
  {
    category: "women",
    prompt: "Which woman hid two Israelite spies in Jericho under stalks of flax?",
    optionA: "Deborah",
    optionB: "Rahab",
    optionC: "Tamar",
    optionD: "Abigail",
    answer: "B",
    explanation: "Rahab hid Joshua's spies on her roof and was saved when Israel conquered Jericho (Joshua 2).",
  },
  {
    category: "women",
    prompt: "Which woman was a judge who led Israel to victory over Canaan?",
    optionA: "Miriam",
    optionB: "Esther",
    optionC: "Anna",
    optionD: "Deborah",
    answer: "D",
    explanation: "Deborah was a prophetess and judge who led Barak and Israel to defeat Sisera (Judges 4–5).",
  },
  {
    category: "women",
    prompt: "Who was the mother of Jesus?",
    optionA: "Mary Magdalene",
    optionB: "Elizabeth",
    optionC: "Mary",
    optionD: "Anna",
    answer: "C",
    explanation: "Mary, a virgin from Nazareth, was chosen by God to be the mother of Jesus (Luke 1:26–31).",
  },
  {
    category: "women",
    prompt: "Who was the mother of John the Baptist?",
    optionA: "Mary",
    optionB: "Anna",
    optionC: "Salome",
    optionD: "Elizabeth",
    answer: "D",
    explanation: "Elizabeth, a relative of Mary, was the mother of John the Baptist (Luke 1:57–60).",
  },
  {
    category: "women",
    prompt: "Which woman was the first to see the risen Jesus?",
    optionA: "Mary, Jesus' mother",
    optionB: "Joanna",
    optionC: "Mary Magdalene",
    optionD: "Salome",
    answer: "C",
    explanation: "Mary Magdalene was the first person to see the risen Jesus (John 20:14–16).",
  },
  {
    category: "women",
    prompt: "Who became queen of Persia and saved the Jewish people from destruction?",
    optionA: "Ruth",
    optionB: "Deborah",
    optionC: "Miriam",
    optionD: "Esther",
    answer: "D",
    explanation: "Esther, a Jewish woman who became queen, courageously revealed Haman's plot to destroy her people (Esther 7).",
  },
  {
    category: "women",
    prompt: "Which woman betrayed Samson by cutting his hair?",
    optionA: "Rahab",
    optionB: "Jezebel",
    optionC: "Delilah",
    optionD: "Gomer",
    answer: "C",
    explanation: "Delilah discovered that Samson's strength was in his hair and had it cut while he slept (Judges 16:19).",
  },
  {
    category: "women",
    prompt: "Who was the wife of Abraham and mother of Isaac?",
    optionA: "Hagar",
    optionB: "Rebekah",
    optionC: "Leah",
    optionD: "Sarah",
    answer: "D",
    explanation: "Sarah was Abraham's wife who bore Isaac in her old age as God promised (Genesis 21:2–3).",
  },
  {
    category: "women",
    prompt: "Who was the wife of Isaac and mother of Jacob and Esau?",
    optionA: "Rachel",
    optionB: "Leah",
    optionC: "Rebekah",
    optionD: "Zilpah",
    answer: "C",
    explanation: "Rebekah was Isaac's wife and the mother of the twin brothers Jacob and Esau (Genesis 25:21–26).",
  },
  {
    category: "women",
    prompt: "Which prophetess led Israel in a song of praise after crossing the Red Sea?",
    optionA: "Deborah",
    optionB: "Huldah",
    optionC: "Miriam",
    optionD: "Anna",
    answer: "C",
    explanation: "Miriam, Moses' sister, led the women in singing and dancing after crossing the Red Sea (Exodus 15:20–21).",
  },
  {
    category: "women",
    prompt: "Who wept and prayed fervently for a child, and God gave her Samuel?",
    optionA: "Rachel",
    optionB: "Hannah",
    optionC: "Leah",
    optionD: "Rebekah",
    answer: "B",
    explanation: "Hannah prayed at Shiloh and God opened her womb; she later dedicated Samuel to the Lord (1 Samuel 1).",
  },
  {
    category: "women",
    prompt: "Who was the wealthy woman from Shunem who provided lodging for Elisha?",
    optionA: "Lydia",
    optionB: "Priscilla",
    optionC: "The Shunammite woman",
    optionD: "Abigail",
    answer: "C",
    explanation: "The Shunammite woman built a room for Elisha; Elisha later raised her son from the dead (2 Kings 4).",
  },
  {
    category: "women",
    prompt: "Who sold purple cloth in Philippi and became one of Paul's first converts in Europe?",
    optionA: "Phoebe",
    optionB: "Priscilla",
    optionC: "Dorcas",
    optionD: "Lydia",
    answer: "D",
    explanation: "Lydia, a dealer in purple cloth from Thyatira, believed and opened her home to Paul (Acts 16:14–15).",
  },
  {
    category: "women",
    prompt: "Which woman in Acts was raised from the dead by Peter after she died?",
    optionA: "Lydia",
    optionB: "Priscilla",
    optionC: "Dorcas (Tabitha)",
    optionD: "Phoebe",
    answer: "C",
    explanation: "Dorcas (Tabitha), known for her good works, died and was raised by Peter in Joppa (Acts 9:36–41).",
  },
  {
    category: "women",
    prompt: "Who was the foreign queen who visited Solomon to test his wisdom?",
    optionA: "Queen of Egypt",
    optionB: "Queen of Babylon",
    optionC: "Queen Vashti",
    optionD: "Queen of Sheba",
    answer: "D",
    explanation: "The Queen of Sheba came to Jerusalem to test Solomon's wisdom and was astonished (1 Kings 10:1–9).",
  },
  {
    category: "women",
    prompt: "Who was the wife of King Ahab, known for promoting Baal worship in Israel?",
    optionA: "Athaliah",
    optionB: "Jezebel",
    optionC: "Gomer",
    optionD: "Delilah",
    answer: "B",
    explanation: "Jezebel, Ahab's Phoenician wife, aggressively promoted Baal worship and persecuted God's prophets (1 Kings 18–21).",
  },
  {
    category: "women",
    prompt: "Which woman anointed Jesus' feet with costly perfume and wiped them with her hair?",
    optionA: "Mary Magdalene",
    optionB: "Joanna",
    optionC: "Mary of Bethany",
    optionD: "Martha",
    answer: "C",
    explanation: "Mary of Bethany anointed Jesus' feet with expensive nard before his burial (John 12:3).",
  },
  {
    category: "women",
    prompt: "Who was the mother-in-law of Ruth?",
    optionA: "Orpah",
    optionB: "Naomi",
    optionC: "Rahab",
    optionD: "Hannah",
    answer: "B",
    explanation: "Naomi was Ruth's Israelite mother-in-law who returned to Bethlehem from Moab (Ruth 1).",
  },
  {
    category: "women",
    prompt: "Who was the wise woman who saved her city by cutting off the head of a rebel?",
    optionA: "Judith",
    optionB: "Jael",
    optionC: "Abigail",
    optionD: "A wise woman of Abel",
    answer: "D",
    explanation: "A wise woman of Abel negotiated with Joab and had Sheba's head thrown over the wall to end the siege (2 Samuel 20:16–22).",
  },
  {
    category: "women",
    prompt: "Who was the widow who gave her last two coins as an offering at the temple?",
    optionA: "Anna the prophetess",
    optionB: "A Samaritan woman",
    optionC: "A poor widow",
    optionD: "Mary of Magdala",
    answer: "C",
    explanation: "Jesus praised the poor widow who gave two small coins, saying she gave more than all the rich (Mark 12:41–44).",
  },

  // ─── Jesus' Parables (22 questions) ─────────────────────────────────────────
  {
    category: "parables",
    prompt: "In the Parable of the Prodigal Son, what did the younger son request from his father?",
    optionA: "A servant's position",
    optionB: "His share of the inheritance",
    optionC: "Permission to travel",
    optionD: "A field to farm",
    answer: "B",
    explanation: "The younger son asked for his share of the estate before his father died (Luke 15:12).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Good Samaritan, who stopped to help the wounded man?",
    optionA: "A priest",
    optionB: "A Levite",
    optionC: "A Samaritan",
    optionD: "A Roman soldier",
    answer: "C",
    explanation: "A Samaritan — despised by Jews — was the one who showed mercy to the wounded man (Luke 10:33–35).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Sower, what happened to seed that fell on rocky ground?",
    optionA: "It produced a hundred times what was sown",
    optionB: "It was eaten by birds",
    optionC: "It was choked by thorns",
    optionD: "It sprouted quickly but withered because it had no root",
    answer: "D",
    explanation: "Seed on rocky ground sprang up quickly but had no deep root and withered in the sun (Matthew 13:5–6).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Ten Virgins, what did the five foolish virgins fail to bring?",
    optionA: "Their lamps",
    optionB: "Extra oil",
    optionC: "Wedding gifts",
    optionD: "Proper clothing",
    answer: "B",
    explanation: "The five foolish virgins did not bring extra oil and missed the bridegroom's arrival (Matthew 25:3–10).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Talents, what did the servant with one talent do with it?",
    optionA: "Traded it and doubled it",
    optionB: "Lost it gambling",
    optionC: "Gave it to the poor",
    optionD: "Buried it in the ground",
    answer: "D",
    explanation: "The one-talent servant buried his master's money out of fear and was rebuked (Matthew 25:18, 24–30).",
  },
  {
    category: "parables",
    prompt: "What does the Parable of the Mustard Seed illustrate?",
    optionA: "The importance of faith in prayer",
    optionB: "The kingdom of heaven starting small and growing large",
    optionC: "How sin spreads through a community",
    optionD: "God's provision for those who trust him",
    answer: "B",
    explanation: "The mustard seed is the smallest of seeds but grows into a large tree — a picture of the kingdom growing (Matthew 13:31–32).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Lost Sheep, what does the shepherd do with the sheep he finds?",
    optionA: "Returns it to the flock silently",
    optionB: "Scolds it for wandering",
    optionC: "Carries it on his shoulders and rejoices",
    optionD: "Ties it up so it cannot wander again",
    answer: "C",
    explanation: "The shepherd places the found sheep on his shoulders and calls his friends to celebrate (Luke 15:5–6).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Lost Coin, how many coins did the woman have originally?",
    optionA: "5",
    optionB: "10",
    optionC: "20",
    optionD: "100",
    answer: "B",
    explanation: "The woman had ten silver coins and searched diligently for the one that was lost (Luke 15:8).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Rich Fool, why was the man called a fool?",
    optionA: "He gave nothing to the poor",
    optionB: "He planned to build bigger barns and live in ease, but died that night",
    optionC: "He worshipped idols instead of God",
    optionD: "He refused to pay his workers",
    answer: "B",
    explanation: "He stored up treasure for himself but was not rich toward God — and God said his soul was required that very night (Luke 12:20).",
  },
  {
    category: "parables",
    prompt: "What is the main lesson of the Parable of the Vineyard Workers (Laborers in the Vineyard)?",
    optionA: "Hard work is always rewarded",
    optionB: "Workers who arrive early deserve more",
    optionC: "God's generosity is not bound by human fairness",
    optionD: "Only those who serve God longest receive the reward",
    answer: "C",
    explanation: "All workers received the same wage regardless of hours worked — showing that God's grace is not earned by human merit (Matthew 20:1–16).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Rich Man and Lazarus, where did Lazarus go after death?",
    optionA: "He was buried with honor",
    optionB: "He was sent to Hades with the rich man",
    optionC: "He was taken to Abraham's side",
    optionD: "He was resurrected immediately",
    answer: "C",
    explanation: "Lazarus was carried by angels to Abraham's side, while the rich man went to Hades in torment (Luke 16:22–23).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Two Sons, which son actually obeyed his father?",
    optionA: "The one who said yes immediately",
    optionB: "The one who said no first but changed his mind and went",
    optionC: "Both sons obeyed",
    optionD: "Neither son obeyed",
    answer: "B",
    explanation: "The son who refused but later went and worked represents those who repent and obey (Matthew 21:28–31).",
  },
  {
    category: "parables",
    prompt: "What does the man do in the Parable of the Hidden Treasure when he finds treasure in a field?",
    optionA: "He tells the landowner about it",
    optionB: "He sells everything he has and buys the field",
    optionC: "He secretly digs it up and keeps it",
    optionD: "He shares it with the poor",
    answer: "B",
    explanation: "He hides it again, then in joy sells all he has to buy that field — showing the surpassing value of the kingdom (Matthew 13:44).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Pharisee and the Tax Collector, who went home justified?",
    optionA: "The Pharisee, because of his fasting and tithing",
    optionB: "Both, because God accepts all prayer",
    optionC: "Neither, because both sinned",
    optionD: "The tax collector, because of his humble prayer",
    answer: "D",
    explanation: "The tax collector beat his chest and said 'God, have mercy on me, a sinner' — and Jesus said he went home justified (Luke 18:13–14).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Great Banquet, why did the host invite strangers off the streets?",
    optionA: "He wanted to show off his wealth",
    optionB: "The originally invited guests all made excuses and refused to come",
    optionC: "His servants made a mistake",
    optionD: "He ran out of food and needed more guests to help",
    answer: "B",
    explanation: "The invited guests refused with excuses, so the master commanded servants to fill the banquet from the roads (Luke 14:18–23).",
  },
  {
    category: "parables",
    prompt: "What does the Parable of the Dragnet (Fishing Net) teach about?",
    optionA: "The importance of evangelism at sea",
    optionB: "God's provision for his people",
    optionC: "Final judgment separating the righteous from the wicked",
    optionD: "How the disciples were called",
    answer: "C",
    explanation: "The net gathers fish of every kind; at the end of the age angels will separate the wicked from the righteous (Matthew 13:47–50).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Unjust Judge, what does the persistent widow represent?",
    optionA: "How God ignores prayer",
    optionB: "The need to pray persistently and not give up",
    optionC: "The importance of justice in society",
    optionD: "Why God delays answering prayer",
    answer: "B",
    explanation: "Jesus told the parable so that his disciples would always pray and not lose heart (Luke 18:1).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Prodigal Son, how did the father respond when he saw the son returning?",
    optionA: "He sent a servant to meet him",
    optionB: "He waited at the door and refused at first",
    optionC: "He ran to him, embraced him, and threw a party",
    optionD: "He demanded repayment before welcoming him",
    answer: "C",
    explanation: "While the son was still far off, the father ran, embraced him, and called for a celebration (Luke 15:20–23).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Wise and Foolish Builders, what happened to the house built on sand?",
    optionA: "It stood firm in the storm",
    optionB: "It slowly sank into the sand over time",
    optionC: "It was moved by a flood",
    optionD: "It collapsed with a great crash when the storm came",
    answer: "D",
    explanation: "The house on sand fell with a great crash, representing those who hear Jesus' words but do not act on them (Matthew 7:27).",
  },
  {
    category: "parables",
    prompt: "What is the Parable of the Leaven (Yeast) compared to?",
    optionA: "The spread of sin in the church",
    optionB: "The kingdom of heaven working through all",
    optionC: "False teaching corrupting the gospel",
    optionD: "The Pharisees' hypocrisy",
    answer: "B",
    explanation: "A woman mixes yeast into three measures of flour until it leavens the whole batch — illustrating how the kingdom permeates everything (Matthew 13:33).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Unforgiving Servant, why was the forgiven servant thrown into prison?",
    optionA: "He stole from his master again",
    optionB: "He refused to forgive a fellow servant a small debt",
    optionC: "He ran away with the forgiven money",
    optionD: "He lied about the debt he owed",
    answer: "B",
    explanation: "After being forgiven a massive debt, the servant refused to forgive a small one — showing that those forgiven by God must forgive others (Matthew 18:28–34).",
  },
  {
    category: "parables",
    prompt: "In the Parable of the Sheep and the Goats, on what basis are people separated?",
    optionA: "How often they attended worship",
    optionB: "Whether they were baptized",
    optionC: "How they treated the poor, hungry, and imprisoned",
    optionD: "Whether they recited the correct creed",
    answer: "C",
    explanation: "Jesus says caring for 'the least of these' is caring for him; those who did not are sent to eternal punishment (Matthew 25:31–46).",
  },

  // ─── Theology (12 questions) ─────────────────────────────────────────────────
  {
    category: "theology",
    prompt: "What is the doctrine of the Trinity?",
    optionA: "God appears in three different forms at different times",
    optionB: "There are three separate gods in Christianity",
    optionC: "God is one being existing eternally as three distinct persons: Father, Son, and Holy Spirit",
    optionD: "God, Jesus, and the church make up a holy trio",
    answer: "C",
    explanation: "The Trinity affirms one God in three co-equal, co-eternal persons: Father, Son, and Holy Spirit.",
  },
  {
    category: "theology",
    prompt: "What does 'justification by faith alone' (sola fide) mean?",
    optionA: "Salvation is earned through good works and faith together",
    optionB: "A person is declared righteous before God through faith in Christ, not by works",
    optionC: "Only those with perfect faith are saved",
    optionD: "Faith in any religion leads to justification",
    answer: "B",
    explanation: "Sola fide, central to the Reformation, teaches that sinners are justified before God by faith alone, not by merit (Romans 3:28).",
  },
  {
    category: "theology",
    prompt: "What is the Hypostatic Union?",
    optionA: "The unity of the Old and New Testaments",
    optionB: "The union of believers with the Holy Spirit",
    optionC: "The marriage of the church with Christ",
    optionD: "Jesus Christ is fully God and fully human in one person",
    answer: "D",
    explanation: "The Council of Chalcedon (451 AD) defined that Christ has two natures — divine and human — united in one person.",
  },
  {
    category: "theology",
    prompt: "What is sanctification?",
    optionA: "The act of being declared holy at the moment of salvation",
    optionB: "The ongoing process of being made holy and transformed into Christlikeness",
    optionC: "The church's act of declaring a person a saint after death",
    optionD: "Water baptism",
    answer: "B",
    explanation: "Sanctification is the lifelong work of the Holy Spirit transforming believers to reflect Christ's character (2 Corinthians 3:18).",
  },
  {
    category: "theology",
    prompt: "What does 'propitiation' mean in Christian theology?",
    optionA: "God's favor shown to the righteous",
    optionB: "Prayer offered on behalf of another",
    optionC: "Christ's sacrifice satisfying God's righteous wrath against sin",
    optionD: "The act of making a public confession of faith",
    answer: "C",
    explanation: "Propitiation means Christ's death fully satisfied God's holy wrath toward sin, turning it away from the believer (1 John 2:2).",
  },
  {
    category: "theology",
    prompt: "What is the doctrine of Original Sin?",
    optionA: "The first sin Adam committed was the worst sin ever committed",
    optionB: "Only Adam and Eve sinned; all others can choose to be sinless",
    optionC: "Sin originated with Lucifer, not humanity",
    optionD: "All humanity is born spiritually dead and inclined toward sin as a result of Adam's fall",
    answer: "D",
    explanation: "Because of Adam's sin, all humanity inherits a sinful nature and guilt before God (Romans 5:12).",
  },
  {
    category: "theology",
    prompt: "What is 'eschatology'?",
    optionA: "The study of the Holy Spirit",
    optionB: "The study of the church and its sacraments",
    optionC: "The branch of theology dealing with last things: death, resurrection, judgment, and eternity",
    optionD: "The study of the origins of Scripture",
    answer: "C",
    explanation: "Eschatology covers biblical teaching on death, the second coming of Christ, final judgment, and the new creation.",
  },
  {
    category: "theology",
    prompt: "What is the Incarnation?",
    optionA: "The Holy Spirit descending at Pentecost",
    optionB: "The resurrection of Jesus from the dead",
    optionC: "The eternal Son of God taking on human flesh",
    optionD: "The birth of the church",
    answer: "C",
    explanation: "The Incarnation is the miracle of God the Son becoming human in the person of Jesus of Nazareth (John 1:14).",
  },
  {
    category: "theology",
    prompt: "What does 'atonement' mean?",
    optionA: "Being at one with other believers in worship",
    optionB: "God's act of forgiving sin through Christ's sacrifice, restoring relationship between God and humanity",
    optionC: "The believer's act of making up for their sins by good deeds",
    optionD: "The church's authority to forgive sin",
    answer: "B",
    explanation: "Atonement refers to Christ's work on the cross, which reconciles sinful humanity to a holy God.",
  },
  {
    category: "theology",
    prompt: "What is 'general revelation'?",
    optionA: "The book of Revelation applying to all generations",
    optionB: "God's special disclosure to prophets and apostles",
    optionC: "Knowledge of God available to all people through creation, conscience, and history",
    optionD: "The final revelation given at the end of the age",
    answer: "C",
    explanation: "General revelation is God's self-disclosure through nature and conscience, accessible to all humanity (Romans 1:19–20).",
  },
  {
    category: "theology",
    prompt: "What is the Great Commission?",
    optionA: "The command to love God and neighbor",
    optionB: "Jesus' command to his disciples to make disciples of all nations",
    optionC: "The Sermon on the Mount's ethical teaching",
    optionD: "The command to keep all 613 Torah laws",
    answer: "B",
    explanation: "In Matthew 28:19–20, Jesus commands his disciples to go and make disciples of all nations, baptizing and teaching them.",
  },
  {
    category: "theology",
    prompt: "What does 'sola scriptura' mean?",
    optionA: "Scripture and church tradition hold equal authority",
    optionB: "Only the original Hebrew and Greek are authoritative",
    optionC: "Scripture alone is the final, supreme authority for faith and practice",
    optionD: "Scripture should only be interpreted by the Pope",
    answer: "C",
    explanation: "Sola scriptura, a Reformation principle, holds that the Bible alone is the ultimate norm for Christian belief and practice.",
  },

  // ─── Church History (12 questions) ──────────────────────────────────────────
  {
    category: "history",
    prompt: "Who nailed the 95 Theses to the Wittenberg church door in 1517, sparking the Reformation?",
    optionA: "John Calvin",
    optionB: "Ulrich Zwingli",
    optionC: "William Tyndale",
    optionD: "Martin Luther",
    answer: "D",
    explanation: "Martin Luther's 95 Theses challenged indulgences and papal authority, igniting the Protestant Reformation.",
  },
  {
    category: "history",
    prompt: "What did the Council of Nicaea (325 AD) primarily address?",
    optionA: "The canonization of the New Testament",
    optionB: "The nature of Christ in response to Arianism",
    optionC: "The authority of the Roman bishop",
    optionD: "The proper date of Easter",
    answer: "B",
    explanation: "Nicaea condemned Arianism and affirmed that Jesus is fully divine — 'of the same substance' as the Father.",
  },
  {
    category: "history",
    prompt: "In what year did the Great Schism divide Christianity into Roman Catholic and Eastern Orthodox churches?",
    optionA: "325",
    optionB: "787",
    optionC: "1054",
    optionD: "1517",
    answer: "C",
    explanation: "The Great Schism of 1054 resulted from disputes over papal authority, the filioque clause, and other theological differences.",
  },
  {
    category: "history",
    prompt: "Who translated the Bible into Latin, producing the Vulgate?",
    optionA: "Augustine",
    optionB: "Origen",
    optionC: "Tertullian",
    optionD: "Jerome",
    answer: "D",
    explanation: "Jerome translated the Bible into Latin at the request of Pope Damasus I; the Vulgate became the standard Bible of the Western church.",
  },
  {
    category: "history",
    prompt: "Who wrote 'Confessions' and 'The City of God', shaping Western Christian theology?",
    optionA: "Aquinas",
    optionB: "Ambrose",
    optionC: "Augustine of Hippo",
    optionD: "Chrysostom",
    answer: "C",
    explanation: "Augustine of Hippo's writings, particularly on grace, sin, and the church, profoundly shaped both Catholic and Protestant theology.",
  },
  {
    category: "history",
    prompt: "Which emperor issued the Edict of Milan in 313 AD, granting Christians religious tolerance?",
    optionA: "Nero",
    optionB: "Diocletian",
    optionC: "Theodosius",
    optionD: "Constantine",
    answer: "D",
    explanation: "Constantine and Licinius issued the Edict of Milan, ending the persecution of Christians and granting freedom of religion.",
  },
  {
    category: "history",
    prompt: "Who founded the Methodist movement in 18th-century England?",
    optionA: "George Whitefield",
    optionB: "John Wesley",
    optionC: "Charles Spurgeon",
    optionD: "William Carey",
    answer: "B",
    explanation: "John Wesley, along with his brother Charles, founded Methodism, emphasizing personal holiness, small group accountability, and evangelism.",
  },
  {
    category: "history",
    prompt: "What is William Tyndale known for in church history?",
    optionA: "Founding the Baptist church",
    optionB: "Translating the Bible into English and being martyred for it",
    optionC: "Writing the Westminster Confession",
    optionD: "Leading the First Great Awakening",
    answer: "B",
    explanation: "Tyndale translated the New Testament into English (1526) and was burned at the stake for heresy in 1536.",
  },
  {
    category: "history",
    prompt: "What were the Crusades?",
    optionA: "Missionary journeys to evangelize Asia",
    optionB: "A series of church councils debating doctrine",
    optionC: "Military campaigns launched by Western Christians to reclaim the Holy Land from Muslim rule",
    optionD: "Persecution campaigns against Protestant reformers",
    answer: "C",
    explanation: "The Crusades (1096–1291) were a series of religious wars launched by the Latin Church to recover Jerusalem and the Holy Land.",
  },
  {
    category: "history",
    prompt: "What was the primary outcome of the Council of Trent (1545–1563)?",
    optionA: "It endorsed the key teachings of the Protestant Reformation",
    optionB: "It defined the doctrine of the Trinity",
    optionC: "It established the date of Easter",
    optionD: "It was the Catholic Church's response to Protestantism, reaffirming Catholic doctrine",
    answer: "D",
    explanation: "The Council of Trent defined Catholic doctrine on Scripture, tradition, justification, and the sacraments in response to Protestant challenges.",
  },
  {
    category: "history",
    prompt: "Who is known as the 'Morning Star of the Reformation' for his early criticism of the Catholic Church?",
    optionA: "Jan Hus",
    optionB: "John Wycliffe",
    optionC: "Peter Waldo",
    optionD: "Martin Luther",
    answer: "B",
    explanation: "John Wycliffe (1320–1384) challenged papal authority and oversaw the first English translation of the Bible, earning the title 'Morning Star of the Reformation.'",
  },
  {
    category: "history",
    prompt: "In what city did the apostles first receive the Holy Spirit at Pentecost?",
    optionA: "Antioch",
    optionB: "Rome",
    optionC: "Corinth",
    optionD: "Jerusalem",
    answer: "D",
    explanation: "The Holy Spirit was poured out on the disciples gathered in Jerusalem on the day of Pentecost (Acts 2:1–4).",
  },
];

async function main() {
  console.log("🌱 Seeding questions...");

  await db.quizAttemptQuestion.deleteMany();
  await db.quizAttempt.deleteMany();
  await db.quizSeenQuestion.deleteMany();
  await db.question.deleteMany();

  await db.question.createMany({
    data: questions,
  });

  const count = await db.question.count();
  const byCategory = await db.question.groupBy({
    by: ["category"],
    _count: { id: true },
  });

  console.log(`✅ Seed complete. Inserted ${count} questions.`);
  for (const row of byCategory) {
    console.log(`   ${row.category}: ${row._count.id}`);
  }
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
