// src/app/terms/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Read the Terms of Service for Faith Companion AI.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-10 md:px-6 md:py-14">
      <div className="rounded-[28px] border border-white/10 bg-white/5 p-8 shadow-2xl backdrop-blur md:p-10">
        <h1 className="text-3xl font-bold text-white md:text-4xl">Terms of Service</h1>

        <div className="mt-6 space-y-5 text-sm leading-7 text-white/75 md:text-base">
          <p>Last updated: April 2026</p>

          <p>
            By accessing or using Faith Companion AI (&ldquo;the Service&rdquo;), you agree to these Terms of Service.
            If you do not agree, do not use the Service.
          </p>

          <h2 className="text-xl font-bold text-white">Use of the Service</h2>
          <p>
            Faith Companion AI provides AI-generated scripture suggestions, prayers, devotionals, and quiz-based
            insights for informational and spiritual encouragement purposes only.
          </p>
          <p>You agree to use the Service:</p>
          <ul className="space-y-1 pl-4">
            {["Lawfully and responsibly", "Without attempting to misuse, disrupt, or exploit the platform"].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-bold text-white">AI-Generated Content Disclaimer</h2>
          <p>
            Content generated by Faith Companion AI is automated and may not always be accurate, complete, or
            appropriate for every situation.
          </p>
          <p>The Service:</p>
          <ul className="space-y-1 pl-4">
            {[
              "Does not provide professional advice",
              "Is not a substitute for pastoral care, counseling, medical advice, legal advice, or other professional services",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>You are responsible for how you interpret and use any content provided.</p>

          <h2 className="text-xl font-bold text-white">Accounts</h2>
          <p>Some features require an account. You are responsible for:</p>
          <ul className="space-y-1 pl-4">
            {["Maintaining access to your email", "All activity under your account"].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>We may suspend or terminate accounts that violate these Terms.</p>

          <h2 className="text-xl font-bold text-white">Payments and Subscriptions</h2>
          <p>Premium features may be offered through recurring or one-time payments. By purchasing:</p>
          <ul className="space-y-1 pl-4">
            {[
              "You agree to the pricing and billing terms shown at checkout",
              "Subscriptions may renew automatically unless canceled",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>Payments are processed by third-party providers such as Stripe.</p>

          <h2 className="text-xl font-bold text-white">No Guarantees</h2>
          <p>We make no guarantees regarding:</p>
          <ul className="space-y-1 pl-4">
            {[
              "Specific outcomes",
              "Personal, spiritual, or emotional results",
              "Availability or accuracy of generated content",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-xl font-bold text-white">Availability</h2>
          <p>We may:</p>
          <ul className="space-y-1 pl-4">
            {[
              "Update, modify, or remove features at any time",
              "Suspend or discontinue the Service without notice",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>We do not guarantee uninterrupted or error-free operation.</p>

          <h2 className="text-xl font-bold text-white">Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, Faith Companion AI shall not be liable for:</p>
          <ul className="space-y-1 pl-4">
            {[
              "Any indirect, incidental, or consequential damages",
              "Any decisions made based on use of the Service",
              "Any loss of data, access, or use",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-1 shrink-0 text-white/30">&bull;</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>Use of the Service is at your own risk.</p>

          <h2 className="text-xl font-bold text-white">Termination</h2>
          <p>
            We reserve the right to suspend or terminate access to the Service at any time if these Terms are violated.
          </p>

          <h2 className="text-xl font-bold text-white">Changes to Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service means you accept any changes.
          </p>

          <h2 className="text-xl font-bold text-white">Governing Law</h2>
          <p>
            These Terms are governed by the laws of your applicable jurisdiction, without regard to conflict of law principles.
          </p>

          <h2 className="text-xl font-bold text-white">Contact</h2>
          <p>
            Questions about these Terms can be sent to:{" "}
            <a
              href="mailto:support@faithcompanionai.com"
              className="underline underline-offset-4 hover:text-white"
            >
              support@faithcompanionai.com
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}